In [2]:
from configparser import ConfigParser

import numpy as np

from datasets import chexnet as cn

config_file = "./chexnet_config.ini"
cp = ConfigParser()
cp.read( config_file )
class_names = cp["DEFAULT"].get( "class_names" ).split( "," )
output_dir = cp["DEFAULT"].get( "output_dir" )
image_source_dir = cp["DEFAULT"].get( "image_source_dir" )
data_entry_file = cp["DEFAULT"].get( "data_entry_file" )


imggen = cn.load_data( image_dir=image_source_dir, data_entry=data_entry_file, train_ratio=70,
                       dev_ratio=10,
                       output_dir=output_dir, img_dim=256, class_names=class_names )

for i in range( 100 ):
    train_set, dev_set, test_set = next( imggen )
    print( np.shape( train_set['data'] ) )
    print( np.shape( train_set['label'] ) )
    # print( train_set['data'] )
    print( train_set['label'][0] )


Total patients = 99 in train/dev/test 69/9/21
Total images = 405 in train/dev/test 275/39/91


(16, 256, 256)
(16, 14)
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


(16, 256, 256)
(16, 14)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


(16, 256, 256)
(16, 14)
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


(16, 256, 256)
(16, 14)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]


(16, 256, 256)
(16, 14)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


(16, 256, 256)
(16, 14)
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
(16, 256, 256)
(16, 14)
[1. 0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


(16, 256, 256)
(16, 14)
[1. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
(16, 256, 256)
(16, 14)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


(16, 256, 256)
(16, 14)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
(16, 256, 256)
(16, 14)
[1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


(16, 256, 256)
(16, 14)
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
(16, 256, 256)
(16, 14)
[0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


KeyboardInterrupt: 